---
- name: Shutdown nodes.
  hosts: nodes
  become: true

  tasks:
    - name: Shut down the system
      community.general.shutdown:

- name: Shutdown control plane.
  hosts: control_plane
  become: true

  tasks:
    - name: Shut down the system
      community.general.shutdown:
        delay: 15  # Wait 15 seconds before shutting down
        msg: "System is shutting down via Ansible!"

---
- name: Shutdown pikvm node.
  hosts: pikvms
  become: true

  tasks:
    - name: Shut down the system
      community.general.shutdown:
        delay: 15  # Wait 15 seconds before shutting down
        msg: "System is shutting down via Ansible!"

---
- name: Shutdown docker nodes.
  hosts: docker
  become: true

  tasks:
    - name: Shut down the system
      community.general.shutdown:
        delay: 15  # Wait 15 seconds before shutting down
        msg: "System is shutting down via Ansible!"