# Raspberry pi role
- src: git@github.com:cole-titze/ansible-role-raspberry-pi.git
  scm: git
  version: master
  name: raspberry-pi

# Docker role
- src: git@github.com:cole-titze/ansible-role-docker.git
  scm: git
  version: main
  name: docker