---
- name: Shutdown nodes.
  hosts: nodes
  become: true

  tasks:
    - name: Shut down the system
      community.general.shutdown:

- name: Shutdown control plane.
  hosts: control_plane
  become: true

  tasks:
    - name: Shut down the system
      community.general.shutdown:
        delay: 10  # Wait 10 seconds before shutting down
        msg: "System is shutting down via Ansible!"