---
- name: Deploy Portainer to Kubernetes
  hosts: control_plane
  become: true
  gather_facts: true

  vars:
    portainer_namespace: portainer
    portainer_hostname: "portainer.kubecluster"

  vars_files:
    - "~/source/ansible-files/vars/cluster_vars.yml"

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:
    - name: Ensure Portainer namespace exists
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: "{{ portainer_namespace }}"

    - name: Add Portainer Helm repository
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: "https://portainer.github.io/k8s/"
        state: present

    - name: Deploy / upgrade Portainer via Helm
      kubernetes.core.helm:
        name: portainer
        chart_ref: portainer/portainer
        release_namespace: "{{ portainer_namespace }}"
        create_namespace: false
        state: present

        values:
          image:
            tag: "lts"

          service:
            type: ClusterIP

          tls:
            force: true

          persistence:
            enabled: true
            storageClass: longhorn

          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/service.serversscheme: https
            hosts:
              - host: "{{ portainer_hostname }}"
                paths:
                  - path: /
                    port: 9443