---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic-mirror
  namespace: magic-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic-mirror
  template:
    metadata:
      labels:
        app: magic-mirror
    spec:
      containers:
        - name: magic-mirror
          image: ghcr.io/cole-titze/containers/magic-mirror:latest
          ports:
            - containerPort: 8082
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: magic-mirror
  namespace: magic-mirror
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: magic-mirror

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: magic-mirror
  namespace: magic-mirror
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mirror.kubecluster`)
      kind: Rule
      services:
        - name: magic-mirror
          port: 8082
  tls:
    certResolver: default