---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
        - name: p-hole
          image: pihole/pihole:latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          env:
            - name: TZ
              value: "America/Chicago"
            - name: DNS1
              value: "127.0.0.1"
            - name: DNS2
              value: "1.1.1.1"
          volumeMounts:
            - name: pihole-config
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-config
          persistentVolumeClaim:
            claimName: pihole-config-pvc
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  type: NodePort
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30095
    - name: dns
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30094
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30093
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 30092
  selector:
    app: pi-hole