---
- name: Configure Code Space
  hosts: control_plane
  gather_facts: false
  become: true
  vars:
    ansible_files_path: "~/source/ansible-files"
  vars_files:
    - "{{ ansible_files_path }}/vars/cluster_vars.yml"

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Create codespace namespace
      k8s:
        name: codespace
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy Codespace Deployment + Service
      k8s:
        definition: "{{ lookup('template', 'codespace-template.yml.j2') }}"
        state: present