---
- name: Setup Docker
  hosts: docker
  become: true
  vars:
    ansible_files_path: "~/source/ansible-files"
  vars_files:
    - "{{ ansible_files_path }}/vars/cluster_vars.yml"
  roles:
    - docker