apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v3.0
          args:
            - "--api.dashboard=true"
            - "--providers.kubernetesIngress=true"
            - "--entrypoints.web.address=:80"
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    app: traefik
  type: NodePort  # use LoadBalancer if you have cloud LB
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: admin
      port: 8080
      targetPort: 8080
      nodePort: 30081