---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: magic-mirror
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magic-mirror
  template:
    metadata:
      labels:
        app: magic-mirror
    spec:
      containers:
        - name: magic-mirror
          image: ghcr.io/cole-titze/containers/magic-mirror:latest
          ports:
            - containerPort: 8082
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 15
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"

---
kind: Service
apiVersion: v1
metadata:
  name: magic-mirror
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 30082
  selector:
    app: magic-mirror

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magic-mirror
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: magic-mirror
                port:
                  number: 8082